[package]
name = "frametool"
version = "0.1.0"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]

[dependencies]
either = "1.0"
interpolate_idents = "0.1.3"
nom = { version = "^2.0", features = ["verbose-errors", "nightly", "regexp", "regexp_macros"] }
regex = "0.1"
